spring.application.name=gorev-yonetim
spring.datasource.url=jdbc:postgresql://localhost:5432/gorevdb
spring.datasource.username=postgres
spring.datasource.password=123456.aZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
