spring.application.name=gorev-yonetim
spring.datasource.url=jdbc:postgresql://localhost:5432/gorevdb
spring.datasource.username=postgres
spring.datasource.password=123456.aZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
file.upload-dir=uploads
spring.security.jwt.secret=3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e
spring.security.jwt.expiration=86400000
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=a72aa0a3760603
spring.mail.password=705c5d9bc59c01
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true